name: ItemOwners
version: 1.0.0
main: com.bfrisco.itemowners.ItemOwners
author: bfrisco
description: Enables players to own and track their items.
api-version: 1.16
softdepend: [SafeTrade, mcMMO]
commands:
  own:
    description: Own an item that is in your hand
    usage: ยง7/<command>
  disown:
    description: Disowns an item that is in your hand
    usage: ยง7/<command>
  itemhistory:
    description: View an items history in reverse-chronological order.
    usage: ยง7/<command> <item id> (page)
  itemsowned:
    description: View the items owned by a specified player.
    usage: ยง7/<command> <player name> (page)

permissions:
  ItemOwners.*:
    description: Gives access to all ItemOwners permisisons
    default: op
    children:
      ItemOwners.own: true
      ItemOwners.disown.own: true
      ItemOwners.disown.all: true
      ItemOwners.list.own: true
      ItemOwners.list.all: true
      ItemOwners.view.own: true
      ItemOwners.view.all: true
  ItemOwners.own:
    description: Allows the player to own items
  ItemOwners.disown.own:
    description: Allows the player to disown their own items
  ItemOwners.disown.all:
    description: Allows the player to disown all items
  ItemOwners.list.own:
    description: Allows the player to list their own items
  ItemOwners.list.all:
    description: Allows the player to list all items
  ItemOwners.view.own:
    description: Allows the player to see their own tools events
  ItemOwners.view.all:
    description: Allows the player to see all tool events